project:
  type: website

website:
  title: "Sample Custom Listings in Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right: 
      - icon: github
        href: https://github.com/kmasiello/quarto-custom-listings

format:
  html:
    theme: cosmo
    css: 
      - styles/featured-styles.css
      - styles/articles-styles.css
      - styles/article-lists-styles.css
    toc: true



